//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualArboretum.Infrastructure.StaticResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualArboretum.Infrastructure.StaticResources.ApplicationTexts", typeof(ApplicationTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do use  `--help` as flag to display help for your command..
        /// </summary>
        internal static string CliGeneralHelp {
            get {
                return ResourceManager.GetString("CliGeneralHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VirtualArboretum does provide different services:\n{0}\n\n Just append `--help` and you shall receive it..
        /// </summary>
        internal static string CliHelpWithCli {
            get {
                return ResourceManager.GetString("CliHelpWithCli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the installed version of your Depositorium, which is: Unknown. {0}.
        /// </summary>
        internal static string CliVersionOption {
            get {
                return ResourceManager.GetString("CliVersionOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Virtual Arboretum is a unique space where your documents, images, and projects are not just stored, but nurtured. Here, they can grow and flourish in a well-organized, vibrant environment. Watch your data blossom and evolve, creating a dynamic and thriving digital ecosystem..
        /// </summary>
        internal static string LongDescriptionOfVirtualArboretum {
            get {
                return ResourceManager.GetString("LongDescriptionOfVirtualArboretum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to administer your digital garden within an attribute-based virtual arboretum..
        /// </summary>
        internal static string ShortDescriptionOfVirtualArboretum {
            get {
                return ResourceManager.GetString("ShortDescriptionOfVirtualArboretum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (\o/)(\o/)(\o/)(\o/)(\o/)
        ///(/|\)(/|\)(/|\)(/|\)(/|\)
        ///(\o/)  _   _   __   (\o/)
        ///(/|\) | \ / | /  \  (/|\)
        ///(\o/) `\ V /&apos;| /\ | (\o/)
        ///(/|\)   \_/  |_||_| (/|\)
        ///(\o/)(\o/)(\o/)(\o/)(\o/)
        ///(/|\)(/|\)(/|\)(/|\)(/|\).
        /// </summary>
        internal static string ShortVAasAsciiArtLogo {
            get {
                return ResourceManager.GetString("ShortVAasAsciiArtLogo", resourceCulture);
            }
        }
    }
}
